CREATE USER IF NOT EXISTS 'admin_user'@'%' IDENTIFIED BY 'admin1234';
CREATE USER IF NOT EXISTS 'read_only'@'%' IDENTIFIED BY 'read1234';
CREATE USER IF NOT EXISTS 'modify_user'@'%' IDENTIFIED BY 'modify1234';

GRANT All PRIVILEGES ON SCHOOL.* TO 'admin_user'@'%';
FLUSH PRIVILEGES ;


